# Generated by Django 2.2 on 2023-07-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_post', models.DateField()),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('mob_no', models.IntegerField(default=False)),
                ('addhar_number', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('Material_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Volt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_post', models.DateField()),
                ('location', models.CharField(max_length=10)),
                ('zip_code', models.IntegerField()),
                ('mob_no', models.IntegerField(default='')),
                ('addhar_number', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('Volt_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
